# Generated by Django 4.2 on 2023-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockteil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDrink', models.IntegerField()),
                ('strDrink', models.CharField(db_index=True, max_length=150)),
                ('idIngredient', models.IntegerField(blank=True, null=True)),
                ('strGlass', models.CharField()),
                ('strInstructions', models.TextField()),
                ('strDrinkThumb', models.URLField()),
                ('strIngredient1', models.CharField()),
                ('strIngredient2', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredientstype',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
